sudo: required
dist: trusty
group: deprecated-2017Q4

# Limit Travis to only the current branch, which prevents Travis from running
# 2 times for each PR (once for "push" and once for "pr"), and prevents Travis
# from running when we make a new git tag during the release promotion process.
branches:
  only:
    - master

# Run multiple commands via "x && y && z" because travis doesn't stop
# when a command in a multiple command yaml block fails, it just marks
# the build as failed and continues with the next command.

# Make sure each job in a build matrix is distinct as far as caching
# is concerned, otherwise we risk corruption:
# https://docs.travis-ci.com/user/caching/#Caches-and-build-matrices

aliases:
  - &go-ver "1.10.x"
  - &set-up-common-bits |
    set -ex
    sudo apt-get -y update
    sudo apt-get -y purge google-cloud-sdk
    sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
    source ~/.bash_profile
    go get -u github.com/golang/dep/cmd/dep

stages:
  - build
  - name: deploy
    if: branch = master

jobs:
  include:
  - stage: build
    env:
      global:
      - "PATH=$PATH:$HOME/local/bin"
      - "CLOUDSDK_CORE_DISABLE_PROMPTS=1"
    os: linux
    language: go
    go: *go-ver
    services: docker
    cache:
      directories:
        - $HOME/local
    before_install: *set-up-common-bits
    before_script:
      - sudo sysctl -w vm.max_map_count=262144
    script:
      - |
        make all

    deploy:
      provider: script
      language: generic
      script: bash build/publish.sh
      skip_cleanup: true
      on:
        branch: master

notifications:
  email: false
