version: '3'
services:
  ui:
    image: davejohnston/ui:latest
    ports:
      - "8081:8081"
  database:
    image: davejohnston/database:latest
    ports:
      - "8082:8082"
  controller:
    image: davejohnston/controller:latest
    ports:
      - "8083:8083"
  edge:
    image: davejohnston/edge:latest
    ports:
      - "8084:8084"
  workstation:
    image: davejohnston/workstation:latest
    ports:
      - "8085:8085"
